dist:
  trusty

sudo:
  false

language:
  node_js

node_js:
  - "lts/*"

git:
  depth:
    3

cache:
  directories:
    - node_modules

addons:
  chrome:
    stable
  firefox:
    latest

notifications:
  email:
    false
